name: plasmidgpt
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - snakemake
  - pandas
  - biopython
  - seaborn
  - transformers
  - tqdm
  - blast
  - ncbi-amrfinderplus
  - prodigal
  - viennarna>=2.6
  - openblas
  - scipy
  - plotly
  - sourmash
  - pip
  - pip:
      - vllm
      - torch
      - torchvision
      - torchaudio
